site:
  short_name: "BeWellnm"
  long_name: "New Mexico's Health Insurance Exchange"
  copyright_period_start: "2019"

  
  social_media:
    facebook_url: ""

contact_center:
  name: "Department of Human Services"
  address: "P.O. Box 91560"
  city: "Albuquerque"
  state_abbreviation: "NM"
  postal_code: "20090"
